config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get 'flights' => 'flights#index'
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight"
  has_many :arriving_flights, foreign_key: :to_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers, reject_if: lambda { |a| a[:name].blank? && a[:email].blank? }
  validates_associated :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings 

  def date_formatted
    self.start_time.strftime("%a %b %d, %Y")
  end

  def self.sorted
    self.order(:start_time)
  end

  def flight_description
    "#{from_airport.code} to #{to_airport.code} on #{start_time}"
  end

  def self.search(params)
    if params
      Flight.where(from_airport_id: params[:from_airport], to_airport_id: params[:to_airport])
    else
      Flight.none
    end
  end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  belongs_to :flight

  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VAILD_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, format: {with: VAILD_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.new
    params[:passengers].to_i.times {@booking.passengers.build}
    @booking.passengers.build if params[:passengers].blank?
  end

  def create
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.confirmation_email(passenger).deliver_later
      end
      redirect_to @booking
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private


    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email, :flight_id])
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airport_options = Airport.all.map{ |i| [i.code, i.id] }
    @date_options = Flight.all.sorted.map{ |n| [n.date_formatted, n.start_time] }
    @flights = Flight.search(params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_new_booking.html.erb
<fieldset>
  <ul>
    <li>Flight No: <%= @flight.id %></li><br />
    <li>From <%= @flight.from_airport.code %></li><br />
    <li>To: <%= @flight.to_airport.code %></li><br />
    <li>Date: <%= @flight.date_formatted %></li><br />
    <li>Flight Duration: <%= distance_of_time_in_words(@flight.duration) %></li><br />
  </ul>
</fieldset>

app/views/bookings/_passengers.html.erb
<%= form_for @booking do |b| %>
  <% i = 1 %>
  <div class="container-fluid">
    <%= b.fields_for :passengers do |p| %>
    <%= render 'shared/error_messages', object: p.object %>
      <h3>Passenger <% i= 1 %></h3>
        <div class="field">
          <%= p.label :name %>
          <%= p.text_field :name %>
          <%= p.label :email %>
          <%= p.email_field :email %>
          <%= p.hidden_field :flight_id, value: params[:flight_id] %>
        </div>
        <% i +=1 %>
    <% end %>
    <%= hidden_field_tag :fiight_id, params[:flight_id] %>
    <%= b.submit "Create Booking", class: "button btn-lg btn-info" %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<%= provide(:title, 'New Booking') %>
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Fly Away</h3>

        </div>
      </div>
      <div class="inner cover">
        <h1 class="cover-heading">Flight Details</h1>
          <%= render 'new_booking'  %>
      </div>
      <div class="row">
        <%= render 'passengers' %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<%= provide(:title, 'Your Booking') %>
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <div class="masthead-brand">Fly Away</div>
          <ul class="nav masthead-nav">
            <li class="active">
              <%= link_to "Home", root_path %>
            </li>
            <li>
              <%= link_to "Log In", "#{}" %>
            </li>

            <li>
              <%= link_to "Sign up", '#' %>
            </li>
            <li>
              <%= link_to "New Flight", root_path %>
            </li>
          </ul>
        </div>
      </div>
      <div class="inner cover">
        <h1>Enjoy your trip!</h1>
          <h3>Booking Info:</h3>
          <fieldset>
            <ul>
              <li>Flight No: <%= @booking.flight.id %></li><br />
              <li>From: <%= @booking.flight.from_airport.code %></li><br />
              <li>To: <%= @booking.flight.to_airport.code %></li><br />
              <li>Date: <%= @booking.flight.date_formatted %></li><br />
              <li>Flight Duration: <%= distance_of_time_in_words(@booking.flight.duraion) %></li><br />
            </ul>
            <h4><%= "Passenger".pluralize(@booking.passengers.count) %></h4>
              <ol>
                <%= @booking.passengers.each do |p| %>
                  <li>
                    <%= p.name %>
                    <%= p.email %>
                  </li>
                  <% end %>
              </ol>
          </fieldset>
      </div>
    </div>
  </div>
</div>

app/views/flights/_search.html.erb
<%= form_tag '/flights', html: {class: 'form-horizontal'}, method: "get" do %>
  <div class="form-group">
    <p><%= select_tag :from_airport, options_for_select(@airport_options, params[:from_airport]), prompt: "From:", class: "form-control form-control-inline" %></p>
    <p><%= select_tag :to_airport, options_for_select(@airport_options, params[:to_airport]), prompt: "To", class: "form-control form-control-inline" %></p><br />
    <p><%= select_tag :start_time, options_for_select(@date_options, params[:start_time]), prompt: "Date", class: "form-control form-control-inline" %></p><br />
    <p><%= select_tag :passengers, options_for_select((1..4), params[:passengers]), prompt: "Passengers", class: "form-control form-control-inline" %></p><br />
    <p class="lead"><%= submit_tag "Search", name: nil, class: "btn btn-default" %></p>
  </div>
<% end %>

app/views/flights/_search_results.html.erb
<%= form_tag new_booking_path, method: "get" do %>
  <h3>Results:</h3>
  <table class="table table-bordered table-condensed">
    <thead>
      <tr>
        <th width="50">Select</th>
        <th width="100">Flight No.</th>
        <th width="100">From</th>
        <th width="100">To</th>
        <th width="150">Date</th>
        <th width="150">Flight Duration</th>
      </tr>
    </thead>
  <% @flights.each do |f| %>
    <tbody>
      <tr>
        <td><%= radio_button_tag :flight_id, f.id %></td>
        <td><%= f.id %></td>
        <td><%= f.from_airport.code %></td>
        <td><%= f.to_airport.code %></td>
        <td><%= f.date_formatted %></td>
        <td><%= distance_of_time_in_words(f.duration) %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <%= hidden_field_tag :passengers, params[:passengers] %>
  <%= submit_tag "Select This Flight", :name => nil, class: "button btn-lg btn-info" %>
  <% end %>

app/views/flights/index.html.erb
<%= provide(:title, 'Flights') %>

<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">Fly Away</h3>
        </div>
      </div>
      <div class="inner cover">
        <h1 class="cover-heading">Where would you like to go?</h1>
          <%= render 'search' %>
      </div>
      <div class="row">
        <% if @flights.present? %>
          <%= render 'search_results' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<% message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>